inherit_gem:
  bixby: bixby_default.yml

AllCops:
  TargetRubyVersion: '2.4.2'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*' # rubocop rspec ignores, but misses the .erb_spec.rb pattern
    - '**/*.gemspec' # these would normally be inherited from bixby
    - 'config/**/*'
    - '**/*/catalog_controller.rb'
Rails/TimeZone:
  Exclude:
    - 'config/initializers/git_sha.rb'
RSpec/MultipleExpectations:
  Exclude:
    - 'spec/features/**/*'
RSpec/ExampleLength:
  Exclude:
    - 'spec/features/**/*'
