language: ruby
sudo: false
cache: bundler
dist: trusty

jdk:
  - oraclejdk8
rvm:
  - 2.4.2
before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database travis_ci_test;' -U postgres;
script:
  - bundle exec rake
services:
  - redis-server
  - postgresql
