terms:
- id:   D.N.P.
  term: D.N.P.
- id:   M.A.
  term: M.A.
- id:   M.B.I.
  term: M.B.I.
- id:   M.M.I.
  term: M.M.I.
- id:   M.N.
  term: M.N.
- id:   M.N.A.
  term: M.N.A.
- id:   M.P.H.
  term: M.P.H.
- id:   M.S.
  term: M.S.
- id:   M.S.N.
  term: M.S.N.
- id:   Ph.D.
  term: Ph.D.
