terms:
  - id: article
    term: Article
  - id: capstone
    term: Capstone
  - id: dissertation
    term: Dissertation
  - id: portfolio
    term: Portfolio
  - id: thesis
    term: Thesis
  - id: other
    term: Other
