terms:
-  id: School of Dentistry
   term: School of Dentistry
-  id: School of Medicine
   term: School of Medicine
-  id: School of Nursing
   term: School of Nursing
-  id: School of Public Health
   term: School of Public Health
