---
development:
  domains:   '*'
  login:    'DATACITE.DCE'
  password: 'mahoniaD0I'
  prefix:   '10.24354'

test:
  domains:   '*'
  login:    'DATACITE.DCE'
  password: 'mahoniaD0I'
  prefix:   '10.5072'

production:
  domains:   '*'
  login:    'DATACITE.DCE'
  password: 'mahoniaD0I'
  prefix:   '10.24354'
