---
:queues:
  - [id_service, 1]
  - [default, 1]

test:
  :concurrency: <%= ENV['SIDEKIQ_CONCURRENCY'] || 5 %>

development:
  :concurrency: <%= ENV['SIDEKIQ_CONCURRENCY'] || 5 %>

production:
  :concurrency: <%= ENV['SIDEKIQ_CONCURRENCY'] || 5 %>
