---
:queues:
  - [id_service, 1]
  - [default, 1]

test:
  :concurrency: ENV['SIDKEKIQ_CONCURRENCY']

development:
  :concurrency: ENV['SIDKEKIQ_CONCURRENCY']

production:
  :concurrency: ENV['SIDKEKIQ_CONCURRENCY']
